name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Install example dependencies
        run: yarn install --cwd example --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: TypeScript
        run: yarn typescript

      - name: Test
        run: yarn test --coverage

      - name: Build
        run: yarn prepare

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
